name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: build
      uses: docker://rockmagicnet/sencha-cmd:4.0.5
      with:
        args: "app build"  
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Docs
        path: build/production/Docs
    
